// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_ci_cd/models/greeting.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_ci_cd/models/greeting.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [Greeting].
///
/// See the documentation for Mockito's code generation for more information.
class MockGreeting extends _i1.Mock implements _i2.Greeting {
  MockGreeting() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String greeting(String? name) =>
      (super.noSuchMethod(Invocation.method(#greeting, [name]), returnValue: '')
          as String);
  @override
  _i3.Future<String> slowGreeting() =>
      (super.noSuchMethod(Invocation.method(#slowGreeting, []),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
  @override
  String toString() => super.toString();
}
